### PR TITLE
feat(oidc): tocompositefieldpath with OpenIDConnectProvider

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: haarchri <chhaar30@googlemail.com>

### Description of your changes

- added patch toCompositeFieldPath for oidc issuer url 
- added OpenIDConnectProvider Resource to use the oidc issuer url
- changed eks version 1.16 to 1.21 because 1.16 is out of support 

Fixes parts of https://github.com/upbound/platform-ref-aws/issues/45

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

`kubectl apply -f examples/cluster.yaml`

```
kubectl get eks
NAME                                   READY   COMPOSITION                         AGE
platform-ref-aws-cluster-g2klb-vwlkn   True    eks.aws.platformref.crossplane.io   62m
```

```
Name:         platform-ref-aws-cluster-g2klb-vwlkn
Namespace:    
Labels:       crossplane.io/claim-name=platform-ref-aws-cluster
              crossplane.io/claim-namespace=api-service
              crossplane.io/composite=platform-ref-aws-cluster-g2klb
Annotations:  crossplane.io/external-name: platform-ref-aws-cluster
API Version:  aws.platformref.crossplane.io/v1alpha1
Kind:         EKS
Metadata:
  Creation Timestamp:  2021-10-30T11:33:16Z
  Generate Name:       platform-ref-aws-cluster-g2klb-
  Generation:          4
  Owner References:
    API Version:     aws.platformref.crossplane.io/v1alpha1
    Controller:      true
    Kind:            CompositeCluster
    Name:            platform-ref-aws-cluster-g2klb
    UID:             b7139690-3f2a-4964-90d2-5eae4cc30cfc
  Resource Version:  7787577
  Self Link:         /apis/aws.platformref.crossplane.io/v1alpha1/eks/platform-ref-aws-cluster-g2klb-vwlkn
  UID:               f01be1a0-2f42-4c08-9271-c0eebe8c9ac3
Spec:
  Composition Ref:
    Name:                     eks.aws.platformref.crossplane.io
  Composition Update Policy:  Automatic
  Id:                         platform-ref-aws-cluster
  Parameters:
    Network Ref:
      Id:  platform-ref-aws-network
    Nodes:
      Count:  3
      Size:   small
  Resource Refs:
    API Version:  identity.aws.crossplane.io/v1beta1
    Kind:         IAMRole
    Name:         platform-ref-aws-cluster-g2klb-2tjxq
    API Version:  identity.aws.crossplane.io/v1beta1
    Kind:         IAMRolePolicyAttachment
    Name:         platform-ref-aws-cluster-g2klb-ngqrz
    API Version:  eks.aws.crossplane.io/v1beta1
    Kind:         Cluster
    Name:         platform-ref-aws-cluster-g2klb-l7skc
    API Version:  identity.aws.crossplane.io/v1beta1
    Kind:         IAMRole
    Name:         platform-ref-aws-cluster-g2klb-68g6b
    API Version:  identity.aws.crossplane.io/v1beta1
    Kind:         IAMRolePolicyAttachment
    Name:         platform-ref-aws-cluster-g2klb-w64hv
    API Version:  identity.aws.crossplane.io/v1beta1
    Kind:         IAMRolePolicyAttachment
    Name:         platform-ref-aws-cluster-g2klb-qjgj6
    API Version:  identity.aws.crossplane.io/v1beta1
    Kind:         IAMRolePolicyAttachment
    Name:         platform-ref-aws-cluster-g2klb-m5xsf
    API Version:  eks.aws.crossplane.io/v1alpha1
    Kind:         NodeGroup
    Name:         platform-ref-aws-cluster-g2klb-2zjwq
    API Version:  identity.aws.crossplane.io/v1alpha1
    Kind:         OpenIDConnectProvider
    Name:         platform-ref-aws-cluster-g2klb-87dsq
  Write Connection Secret To Ref:
    Name:       b7139690-3f2a-4964-90d2-5eae4cc30cfc-eks
    Namespace:  upbound-system
Status:
  Conditions:
    Last Transition Time:  2021-10-30T12:31:31Z
    Reason:                Available
    Status:                True
    Type:                  Ready
  Connection Details:
    Last Published Time:  2021-10-30T12:35:34Z
  Eks:
    Oidc:  https://oidc.eks.us-west-2.amazonaws.com/id/4A468D686B1A4B1964C053F2870337C2

```

```
kubectl get OpenIDConnectProvider
NAME                                   READY   SYNCED   URL
platform-ref-aws-cluster-g2klb-87dsq   True    True     https://oidc.eks.us-west-2.amazonaws.com/id/4A468D686B1A4B1964C053F2870337C2
```

### CODE REVIEW

**Review by jbw976 — COMMENTED** [review]
Very cool to see this contribution and effort from you @haarchri!! A couple high level questions to help me understand a bit better:

* Does this depend on a newer version of provider-aws (e.g. the latest patch of v0.20.1)?
* Does this work for the general mainstream vanilla case where the user isn't using any fancy auth/openID/etc.? e.g. will this still continue working for everyone, even if they are testing it out in a bare bones ephemeral dev env?

**Comment by haarchri** [comment]
`Does this depend on a newer version of provider-aws (e.g. the latest patch of v0.20.1)?`
you are right for OpenIDConnectProvider we need minimum 0.19.0 - i will update if you agress

`Does this work for the general mainstream vanilla case where the user isn't using any fancy auth/openID/etc.? e.g. will this still continue working for everyone, even if they are testing it out in a bare bones ephemeral dev env?`
OpenIDConnectProvider will configure IAM IdentityProvider - think this feature not blocks someone in dev envs - we get very often in crossplane community the question how we can configure in a automation way the OpenIDConnectProvider - few examples:

- https://github.com/crossplane/provider-aws/issues/796 
- https://crossplane.slack.com/archives/CEG3T90A1/p1632229361004200?thread_ts=1629552453.403400&cid=CEG3T90A1
- https://crossplane.slack.com/archives/CEG3T90A1/p1631023761224700?thread_ts=1631017850.222900&cid=CEG3T90A1

good point is that we can reference the platform-ref-aws here and we can show toCompositeFieldPath - what do you think ?

**Comment by jbw976** [comment]
Ah got it - thank you for confirming a little more details about the reasoning for this change @haarchri! Sounds good to me - go ahead and include the bump on the provider-aws dependency in https://github.com/upbound/platform-ref-aws/blob/main/crossplane.yaml#L93, then we should be good to go with this change! :)

**Comment by haarchri** [comment]
@jbw976 done

**Review by jbw976 — APPROVED** [review]
Thank you for making this addition @haarchri!!

**Comment by jbw976** [comment]
We'll follow up in #57 to get a new version released that includes this PR :)

**Comment by premsayee** [comment]
@haarchri, Appreciate the work here. This PR fixed a few of the errors I encountered.

**Pull request merged**
