### PR TITLE
Bump kube-prometheus-stack chart to latest

### PR DESCRIPTION
**Pull request by turkenh**
### Description of your changes

Pushes kube-prometheus-stack chart to the latest version.
Also testing new e2e workflow.

I have:

- [x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested

With e2e workflow.

### CODE REVIEW

**Comment by turkenh** [comment]
End-to-end tests which were previously failing with [this issue](https://github.com/upbound/platform-ref-aws/issues/84) seem to be working now. It passed all 3 of 3 tries 🎉 

Apparently, [this PR](https://github.com/upbound/provider-aws/pull/140) did the trick.

**Review by ytsarev — APPROVED** [review]
Great news! 👍

**Pull request merged**
