### PR TITLE
Update dependsOn list with smaller providers

### PR DESCRIPTION
**Pull request by ezgidemirel**
### Description of your changes
This PR is an example usage of smaller providers in a configuration.

Fixes #

I have:

- [ ] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.

### How has this code been tested
Built and push the configuration and created cluster-claim.

### CODE REVIEW

**Comment by ulucinar** [comment]
Heads up: The triggered test will fail because of a harmful interplay between https://github.com/upbound/provider-aws/pull/728 and the Crossplabe RBAC manager.

**Review by ytsarev — APPROVED** [review]
Thanks for the updates, LGTM!

**Pull request merged**
